name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: mold
        version: 1.0
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check clippy
      run: cargo clippy
    - name: Check formatting
      run: cargo fmt --check
