name: Publish

on:
  push:
    branches: [ "stable" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: ningenMe/setup-rustup@v1.1.0
    - run: sudo apt-get install -qq --yes --force-yes musl-tools mold gcc-mingw-w64 gcc-multilib gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 clang-13 llvm-13 lld-13 llvm-dev gcc-mingw-w64-i686-win32 gcc-mingw-w64-x86-64-win32
    - run: cargo install cargo-xwin --locked
    - run: cargo install cbindgen --locked
    - run: echo "XWIN_ARCH=x86,x86_64,aarch64,aarch" >> "$GITHUB_ENV"

    - name: Create release dir
      run: rm -fr target/github-release && mkdir -p target/github-release

    - name: Build for x86_64-unknown-linux-gnu
      run: rustup target add x86_64-unknown-linux-gnu &&
           cargo build --verbose --release --target x86_64-unknown-linux-gnu &&
           cp target/x86_64-unknown-linux-gnu/release/libimagecdylib
              target/github-release/libimagecdylib.x86_64-unknown-linux-gnu

    - name: Build for x86_64-unknown-linux-gnu
      run: rustup target add x86_64-unknown-linux-musl &&
           cargo build --verbose --release --target x86_64-unknown-linux-musl &&
           cp target/x86_64-unknown-linux-musl/release/libimagecdylib
              target/github-release/libimagecdylib.x86_64-unknown-linux-musl

    - name: Build for i586-unknown-linux-gnu
      run: rustup target add i586-unknown-linux-gnu &&
           cargo build --verbose --release --target i586-unknown-linux-gnu --no-default-features --features minreq &&
           cp target/i586-unknown-linux-gnu/release/libimagecdylib
              target/github-release/libimagecdylib.i586-unknown-linux-gnu

    - name: Build for i686-unknown-linux-gnu
      run: rustup target add i686-unknown-linux-gnu &&
           cargo build --verbose --release --target i686-unknown-linux-gnu &&
           cp target/i686-unknown-linux-gnu/release/libimagecdylib
              target/github-release/libimagecdylib.i686-unknown-linux-gnu

    - name: Build for x86_64-pc-windows-gnu
      run: rustup target add x86_64-pc-windows-gnu &&
           cargo build --verbose --release --target x86_64-pc-windows-gnu &&
           cp target/x86_64-pc-windows-gnu/release/imagecdylib.dll
              target/github-release/imagecdylib.x86_64-pc-windows-gnu.dll

    - name: Build for x86_64-pc-windows-msvc
      run: rustup target add x86_64-pc-windows-msvc &&
           cargo xwin build --verbose --release --target x86_64-pc-windows-msvc &&
           cp target/x86_64-pc-windows-msvc/release/imagecdylib.dll
              target/github-release/imagecdylib.x86_64-pc-windows-msvc.dll

    - name: Build for i686-pc-windows-gnu
      run: rustup target add i686-pc-windows-gnu &&
           cargo build --verbose --release --target i686-pc-windows-gnu &&
           cp target/i686-pc-windows-gnu/release/imagecdylib.dll
              target/github-release/imagecdylib.i686-pc-windows-gnu.dll

    - name: Build for i686-pc-windows-msvc
      run: rustup target add i686-pc-windows-msvc &&
           cargo xwin build --verbose --release --target i686-pc-windows-msvc &&
           cp target/i686-pc-windows-msvc/release/imagecdylib.dll
              target/github-release/imagecdylib.i686-pc-windows-msvc.dll

    - name: Generate C bindings
      run: cbindgen -c Cbindgen.toml --lang C -o target/github-release/imagecdylib.h

    - uses: colathro/crate-version@2.0.0
      id: crate-version

    - uses: ncipollo/release-action@v1
      with:
        tag: v${{ steps.crate-version.outputs.version }}
        artifacts: "target/github-release/*"
        commit: stable
        generateReleaseNotes: true
